name: Release
on: [push, pull_request]

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install deps (npm ci)
        shell: bash
        run: npm ci

      - run: npm run build

      - name: Pack dry-run
        run: npm pack --dry-run

      - name: Semantic Release
        run: npx semantic-release --extends ./release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
