name: Run Tests

on:
  workflow_run:
    workflows: ['Setup Dependencies']
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node with caching
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Automatically caches node_modules

      # Install dependencies if cache missed
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm run test
